### ISSUE TITLE
Class 'AbstractDocumentQuery<T, TSelf>' incorrectly implements interface 'QueryEventsEmitter'

### ISSUE THREAD

**Issue by pittsvillesc** [ravendb/ravendb-nodejs-client#213]
I'm getting an error trying to implement with Angular. 

Here is the error:
ERROR in node_modules/ravendb/dist/Documents/Session/AbstractDocumentQuery.d.ts:44:31 - error TS2420: Class 'AbstractDocumentQuery<T, TSelf>' incorrectly implements interface 'QueryEventsEmitter'.
  Type 'AbstractDocumentQuery<T, TSelf>' is missing the following properties from type 'QueryEventsEmitter': off, rawListeners

44 export declare abstract class AbstractDocumentQuery<T extends object, TSelf extends AbstractDocumentQuery<T, TSelf>> extends EventEmitter implements QueryEventsEmitter, IAbstractDocumentQuery<T> {
                                 ~~~~~~~~~~~~~~~~~~~~~
node_modules/ravendb/dist/Documents/Session/DocumentQuery.d.ts:36:22 - error TS2420: Class 'DocumentQuery<T>' incorrectly implements interface 'IDocumentQuery<T>'.
  Type 'DocumentQuery<T>' is missing the following properties from type 'IDocumentQuery<T>': off, rawListeners

36 export declare class DocumentQuery<T extends object> extends AbstractDocumentQuery<T, DocumentQuery<T>> implements IDocumentQuery<T> {
                        ~~~~~~~~~~~~~
node_modules/ravendb/dist/Documents/Session/RawDocumentQuery.d.ts:9:22 - error TS2420: Class 'RawDocumentQuery<T>' incorrectly implements interface 'IRawDocumentQuery<T>'.
  Type 'RawDocumentQuery<T>' is missing the following properties from type 'IRawDocumentQuery<T>': off, rawListeners

9 export declare class RawDocumentQuery<T extends object> extends AbstractDocumentQuery<T, RawDocumentQuery<T>> implements IRawDocumentQuery<T> {

my implementation:

raven-db.service.ts:
```
export class RavenDBService {
  private store = new DocumentStore(
    ["http://127.0.0.1:8080/"], "PES"
  );
  constructor() { 
    this.store.initialize();    
  }

  getSession() : any {
    return this.store.openSession();
  }
}
```
form-axample.component.ts:
```
...
constructor(private fb: FormBuilder, private store: RavenDBService) { }

  async onSubmit() {
    var session = this.store.getSession();
    await session.store(this.addressForm);
    await session.saveChanges();

    alert('Thanks!');
  }
}
```

**Comment by gregolsky** [comment]
Hello @pittsvillesc,

Are you trying to use RavenDB client on the frontend (asking because I noticed that alert() call and component code)? If so, that is not possible.

It can be used in the backend with the Node.js platform. It will not run in the browser.

If that is not the case please attach a full example project and commands showing the issue.

**Comment by rugadillo** [comment]
Thank you for the quick response.  I was foolishly operating under the impression that the library was a "client-side" api because of it's name (embarrassed). 

My intention was to look into creating an admin app with electron (just experimenting).  I will put the RavenDB.Client back in some express code and give it another shot.

Dziękuję Ci!

**Comment by pittsvillesc** [comment]
Oops, wrong GitHub account.  Thanks you again!
