### ISSUE TITLE
Getting started error

### ISSUE THREAD

**Issue by y-nk** [ravendb/ravendb-nodejs-client#295]
Following the getting started on the README, I'm hitting:

```
An exception occurred while contacting https://[redacted[.ravendb.cloud/databases/[redacted]/bulk_docs? . \n' +
    'TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"\n' +
```

I'm running your client in a lambda using node 14.

**Comment by gregolsky** [comment]
Might be the error is a bit misleading (cc @ml054), but I think you might have tried to access a secured instance using code for non-secured one? RavenDB Cloud clusters are secured and you need to supply a client certificate in order to access them.

Can you check if these help?
https://ravendb.net/docs/article-page/5.3/csharp/cloud/cloud-security#using-the-initial-client-certificate
https://github.com/ravendb/ravendb-nodejs-client#working-with-secured-server

If that's not the case can you please share a code snippet presenting the issue?

**Comment by ayende** [comment]
Did you set the certificate properly? That is likely the reason for the error.

**Comment by y-nk** [comment]
yes, i could unlock myself with using the certificate but the getting started example didn't mention about it. i think it's mostly docs at this point.

**Comment by gregolsky** [comment]
Thank you @y-nk . I moved these to our internal bug tracker. If you'd like you can track the progress here:
https://issues.hibernatingrhinos.com/issue/RDBC-546
https://issues.hibernatingrhinos.com/issue/RDBC-545
